config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'dashboards/mytasks', as: "mytasks"
  get 'dashboards/myjobs', as: "myjobs"
  get 'dashboards/myprofile', as: "myprofile"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get '/about', to: 'pages#about'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :tasks, only: [:index, :new, :create, :show] do
    resources :bookings, only: [:create, :show, :destroy] do
      resources :reviews, only: [ :new, :create, :update]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :task
  has_one :review
  
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :rating, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  # CATEGORIES = {
  #   "gardening" => '<i class="fa-solid fa-tree"></i>',
  #   "handyman" => '<i class="fa-solid fa-hammer"></i>',
  #   "cleaning" => '<i class="fa-solid fa-broom"></i>',
  #   "other" => '<i class="fa-solid fa-clipboard-question"></i>'
  # }
  belongs_to :user
  has_one_attached :photo
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  belongs_to :user
  has_one_attached :photo
  validates :title, presence: true, uniqueness: true
  validates :location, :price, :description, presence: true

  include PgSearch::Model

  pg_search_scope :task_search,
  against: [ :title, :description, :location ],
  using: {
    tsearch: { prefix: true }
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks
  has_many :bookings
  has_one_attached :photo

  # do they have many booking through the task
  # also do they have many booking as well.
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
  
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # def new
  #   @task = Task.find(params[:task_id])
  #   @booking = Booking.new
  # end

  def create
    @task = Task.find(params[:task_id])
    @booking = Booking.new
    @booking.user = current_user
    @booking.task = @task
    if @booking.valid?
      @booking.save
      redirect_to task_booking_path(@task, @booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @task = @booking.task
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    @task = @booking.task
    redirect_to task_path(@task)
  end

  private

  def booking_params
    params.require(:booking).permit(:id)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_user, only: %i[mytasks myjobs myprofile]
  def mytasks
    @tasks = @user.tasks
  end

  def myjobs
    @jobs = @user.bookings
  end

  def myprofile
    @user
  end

  def set_user
    @user = current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @tasks = Task.all[0..11]
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
       redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def review_params
    params.require(:review).permit(:rating)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  skip_before_action :authenticate_user!, only: :show

  def index
    if params[:query].present?
      @tasks = Task.task_search(params[:query])
    else
      @tasks = Task.all
    end

    @markers = @tasks.geocoded.map do |task|
      {
        lat: task.latitude,
        lng: task.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {task: task}),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @user = current_user
    @task.user = @user
    if @task.valid?
      @task.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @task = Task.find(params[:id])
    if @task.geocoded?
      @marker = [{
        lat: @task.latitude,
        lng: @task.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {task: @task}),
        marker_html: render_to_string(partial: "marker")
      }]
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :location, :price, :photo, :task_due_by)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

<%= simple_form_for([@task, @booking]) do |f| %>
  <%= f.association :task %>
  <%= f.submit %>
<% end %>

<%# task.user (person who MADE the task)
task.booking.user (person who FILLS the task) %>

app/views/bookings/show.html.erb
<h1>Booking Confirmed!</h1>

<div class="p-4">
  <p>Task: <%= @booking.task.title %></p>
  <p>Created by: <%= @booking.task.user.username %></p>
  <p>To be completed by: <%= @booking.user.username %></p>
  <%= link_to "Delete booking", task_booking_path(@task,@booking), class: "btn btn-warning", data: {turbo_method: :delete, turbo_confirm: "Delete ?"} %>
  <%= link_to "Back to Home", root_path, class: "btn btn-success", data: {turbo_method: :delete, turbo_confirm: "Delete ?"} %>
</div>

app/views/dashboards/myjobs.html.erb
<div class = "list-activities">
  <h1>Jobs I'm assisting with:</h1>
  <p>Track all the jobs you need to get done, make sure to check the due date.</p>
  <div class="">
    <div class="card-container mt-5 row">
      <div class="list-group">
        <% @jobs.each do |job| %>
          <a href=<%= task_path(job.task)%> class="list-group-item list-group-item-action"><%=job.task.title%> for <%=job.task.user.username%> due by: <%=job.task.task_due_by%>.</a>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/myprofile.html.erb
<% task = @user.tasks.length %>
<% jobs = @user.bookings.length %>

<div class="profile-user">
<h1 class="mb-5">How others see you: <%= @user.username %> ⭐</h1>
  <div class="d-flex justify-content-between">
    <div class="m-4">
      <i class="fa-solid fa-trophy"></i>
      <h2><%= jobs %> jobs posted</h2>
    </div>
    <div class="m-4">
      <i class="fa-solid fa-hammer"></i>
      <h2><%= task %> tasks to be done</h2>
    </div>
  </div>
</div>

<div class="fa-3x">
  <%= link_to new_task_path do %>
    <i class="fa-solid fa-circle-plus fa-beat"></i>
  <%end%>
  <i class="fa-solid fa-heart fa-beat"></i>
  <i class="fa-solid fa-heart fa-beat" style="--fa-animation-duration: 0.5s;"></i>
  <i class="fa-solid fa-heart fa-beat" style="--fa-animation-duration: 2s;"></i>
  <i class="fa-solid fa-heart fa-beat" style="--fa-beat-scale: 2.0;"></i>
</div>

<div  class="main-content">

            <!--########################## Profile Starts Here ############################# -->

            <div class="profile-head">
               <div class="row vh-100">
                   <div class="col-xl-6 text-center mx-auto align-self-center ">
                        <div class="imgcover mb-4">
                            <img src="https://static.vecteezy.com/system/resources/previews/020/765/399/original/default-profile-account-unknown-icon-black-silhouette-free-vector.jpg"
                            class="rounded-circle"
                            style="width: 150px; height: 150px;
                            object-fit: cover;"/>
                            <div class="m-4">
                              <%= link_to "Edit profile", edit_user_registration_path, class: "btn btn-info" %>
                              <h1><%= @user.username %></h1>
                              <h2>⭐⭐⭐⭐⭐</h2>
                            </div>
                        </div>
                        <b class="fs-6">Hello I am, <%= @user.username %></b>
                        <h1 class="fw-bold mb-4 fs-1">Full Stack Develper</h1>
                        <p>This section would be linked to the description about user in the user model which will be linked by the edit profile form</p>
                        <ul>
                            <li></li>
                        </ul>
                    </div>
               </div>
            </div>

             <div id="about" class="about px-4 bg-white py-5 rounded">
                <div class="titie-row row mb-3">
                    <h2 class="fw-bolder text-center">About Me</h2>
                </div>
                <div class="row">
                    <div class="col-md-7">
                        <p class="text-center"><b>I am, <%= @user.username %></b></p>
                        <p class="pt-2 fs-6 text-justify text-center">this section would be a description about myself and what skills i am capable of doing</p>

                        <h4 class=" fs-5 my-3 mt-4 fw-bolder text-center">What is my skill level ?</h4>
                        <p class="text-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ipsum sit nibh amet egestas tellus.</p>

                        <div class="row skill-set">
                            <div class="col-md-6 py-3">
                               <h6 class="fw-bold"><i class="fa-solid fa-toolbox"></i></h6>
                                <div class="progress">
                                  <div class="progress-bar bg-primary" role="progressbar" aria-label="Example with label" style="width: 75%;" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">75%</div>
                                </div>
                            </div>
                             <div class="col-md-6 py-3">
                                <h6 class="fw-bold"><i class="fa-solid fa-jet-fighter-up"></i></h6>
                                <div class="progress">
                                  <div class="progress-bar bg-primary" role="progressbar" aria-label="Example with label" style="width: 65%;" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100">60%</div>
                                </div>
                            </div>
                            <div class="col-md-6 py-3">
                                <h6 class="fw-bold"><i class="fa-solid fa-broom"></i></h6>
                                <div class="progress">
                                  <div class="progress-bar bg-primary" role="progressbar" aria-label="Example with label" style="width: 90%;" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100">90%</div>
                                </div>
                            </div>

                             <div class="col-md-6 py-3">
                                <h6 class="fw-bold"><i class="fa-solid fa-truck-fast"></i></h6>
                                <div class="progress">
                                  <div class="progress-bar bg-primary" role="progressbar" aria-label="Example with label" style="width: 85%;" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100">85%</div>
                                </div>
                            </div>

                            <div class="col-md-6 py-3">
                                <h6 class="fw-bold"><i class="fa-solid fa-plane"></i></h6>
                                <div class="progress">
                                  <div class="progress-bar bg-primary" role="progressbar" aria-label="Example with label" style="width: 55%;" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100">55%</div>
                                </div>
                            </div>

                            <div class="col-md-6 py-3">
                                <h6 class="fw-bold"><i class="fa-solid fa-dumbbell"></i></h6>
                                <div class="progress">
                                  <div class="progress-bar bg-primary" role="progressbar" aria-label="Example with label" style="width: 66%;" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100">66%</div>
                                </div>
                            </div>

                            <div class="col-md-6 py-3">
                                <h6 class="fw-bold"><i class="fa-solid fa-basket-shopping"></i></h6>
                                <div class="progress">
                                  <div class="progress-bar bg-primary" role="progressbar" aria-label="Example with label" style="width: 82%;" aria-valuenow="82" aria-valuemin="0" aria-valuemax="100">82%</div>
                                </div>
                            </div>

                            <div class="col-md-6 py-3">
                                <h6 class="fw-bold"><i class="fa-solid fa-screwdriver-wrench"></i></h6>
                                <div class="progress">
                                  <div class="progress-bar bg-primary" role="progressbar" aria-label="Example with label" style="width: 45%;" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100">45%</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <img src="assets/images/profile.jpg" alt="">
                    </div>
                </div>
            </div>

app/views/dashboards/mytasks.html.erb
<div class="list-activities">
  <h1>Tasks I need done:</h1>

  <% @tasks.each do |task| %>
    <div class="card-container mt-5 row g-3">
      <% @tasks.each do |task| %>
        <%= link_to(task_path(task), class: "col-lg-3 col-md-4 col-12") do %>
          <%= render "/shared/task_card", task: task %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Worknest</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <% if controller_name == 'pages' && action_name == 'home' %>
      <%= yield %>
    <% else %>
      <div class="container mt-5 min-height">
        <%= yield %>
      </div>
    <% end %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>this is my about page</h1>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1505798577917-a65157d3320a?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);
width: 100%">
  <div class="p-5">
    <h1>Worknest</h1>
    <p>Find the right work for you!</p>
    <p>Or find the right person to work for you!</p>
    <p>Improve your work. Improve your nest. </p>
  </div>
</div>

<div class="container">
  <div class="card-container mt-5 row">
    <% @tasks.each do |task| %>
      <%= link_to(task_path(task), class: "col-lg-3 col-md-6 col-12") do %>
        <%= render "/shared/task_card", task: task %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= simple_form_for [@booking, @review] do |f| %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div>
    <p> Made by: </p>
    <div class="footer-links">
      <a href="https://github.com/Lamarr1997/worknest"><i class="fab fa-github"></i></a>
      <a href="https://github.com/Lamarr1997"><i class="fa-sharp fa-solid fa-person"></i></a>
      <a href="https://github.com/zzdevzz"><i class="fa-solid fa-person"></i></a>
      <a href="https://github.com/Glowrare1"><i class="fa-solid fa-person-dress"></i></a>
      <a href="https://www.linkedin.com/school/le-wagon/"><i class="fab fa-linkedin"></i></a>
    </div>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div>
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "Worknest-Logo-Clean-simple-01.png" %>
      <% end %>
      <h2 class="navbar-name">Worknest</h2>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Browse Tasks", tasks_path, class: "nav-link" %>
          </li>
           <li class="nav-item">
            <%= link_to "Make New Task", new_task_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://static.vecteezy.com/system/resources/previews/020/765/399/original/default-profile-account-unknown-icon-black-silhouette-free-vector.jpg", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Profile", myprofile_path, class: "dropdown-item" %>
              <%= link_to "My Jobs", mytasks_path, class: "dropdown-item" %>
              <%= link_to "My Commitments", myjobs_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_task_card.html.erb
  <% if task.photo.attached? %>
    <% photo_url = cl_image_path task.photo.key, crop: :fill %>
  <% else %>
    <% photo_url = image_path "https://source.unsplash.com/random/?1,#{task.title}" %>
  <% end %>

<div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <%= image_tag photo_url, style: "width: 100%; height: 60%" %>
      <div class="p-3 text-content mb-3">
        <h2><%= task.title %></h2>
        <p><strong><%=task.user.username%></strong> will pay: <strong>£<%= task.price %></strong></p>
        <p class="truncate"><%= task.description %>...</p>
      </div>
    </div>
    <div class="flip-card-back p-4 text-content">
      <h2><%= task.title %></h2>
      <p><strong><%=task.user.username%></strong> will pay: <strong>£<%= task.price %></strong></p>
      <p><%= task.description %></p>
      <p><i class="fa-solid fa-location-dot"></i> <%= task.location %></p>
      <p><i class="fa-solid fa-calendar-check"></i> Needed by: <%= task.task_due_by %></p>
    </div>
  </div>
</div>

app/views/tasks/_images_carousel.html.erb
  <% if task.photo.attached? %>
    <% photo_url = cl_image_path task.photo.key, crop: :fill %>
  <% else %>
    <% photo_url = image_path "https://source.unsplash.com/random/?1,#{task.title}" %>
  <% end %>


<div id="carouselExampleControls" class="carousel slide h-75" data-bs-ride="carousel">
  <div class="carousel-inner h-100">
    <div class='carousel-item active data-bs-interval="500"'>
      <%= image_tag photo_url, class: "d-block w-100" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "https://source.unsplash.com/random/?2,#{task.title}", class: "d-block w-100" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "https://source.unsplash.com/random/?3,#{task.title}", class: "d-block w-100" %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/tasks/_info_window.html.erb
<%= link_to task_path(task) do %>
  <div class="rounded-circle info-window">
    <h2><%= task.title %></h2>
    <p><%= task.location %></p>
    <p><%= task.price%></p>
    <p> Click on card for more info. </p>
  </div>
<% end %>

app/views/tasks/_marker.html.erb
<div class="badge rounded-pill fs-6">
  <%= image_tag "Worknest-Logo-Clean-simple-01.png", style: "width: 75px; height: 75px;"%>
</div>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/index.html.erb
<h1>Tasks you can help with</h1>

<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: tasks_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type a keyword"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="card-container mt-5 row g-3">
  <% @tasks.each do |task| %>
    <%= link_to(task_path(task), class: "col-lg-3 col-md-4 col-12") do %>
      <%= render "/shared/task_card", task: task %>
    <% end %>
  <% end %>
</div>

<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/tasks/new.html.erb
<h1>What do you need done?</h1>
<p>Be as descriptive as possible. Image upload coming soon.</p>

<%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :location %>
  <%= f.input :price %>
  <%= f.input :description %>
  <%= f.input :photo, as: :file %>
  <%= f.input :task_due_by, as: :string,
            input_html: { data: { controller: "datepicker" } } %>
  <%= f.submit "submit" %>
<% end %>

app/views/tasks/show.html.erb
<div class="task-container blue-line">
    <h1><%= @task.title%></h1>
    <div class="d-flex show-container gap-3 p-3">
      <div class="d-flex flex-column w-50 h-100 gap-3">
        <%= render "/tasks/images_carousel", task: @task %>
         <p><%= @task.description %></p>
      </div>
      <div class = "d-flex flex-column w-50 h-100">
        <div class="show-actions mb-3 d-flex justify-content-sm-around">
          <%= button_to 'Back to all tasks', root_path, class: "btn btn-info" %>
          <%= button_to "Visit #{@task.user.username}'s profile", root_path, class: "btn btn-info" %>
          <%= button_to 'Book Now', task_bookings_path(@task), class: "btn btn-primary" %>
        </div>
        <div style="width: 100%; height: 600px;"
          data-controller="map"
          data-map-markers-value="<%= @marker.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
</div>